basic:
    name: 'RRC Polytech'
    environments:
        production: 'https://www.rrc.ca'
        staging: 'https://dev-83829-rrc.pantheonsite.io'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /legal
        - /campuses
        - /future-students
        - '/?s=nurse'
        - '/thankyou/?form_key=acecooppartner'
        - /subscriptions
        - '/subscriptions/?id=mce-group%5B9489%5D-9489-3'
        - /404
        - /part-time/contact
        - /research-kitchen
        - /janes
        - /parking/bike/security
        - /alumni/instagram
        - /marcom/news
        - /news
        - /news/category/alumni
        - /its/help-resources/student-printing/install-college-printer-on-your-device
        - /news/2023/02/03/early-child-development-resource-continues-to-grow-with-global-reach
        - /part-time
        - /part-time/programs/information-technology
        - /student
        - '/news?s=nurse&post_type=post'
        - /news/404
        - /explore
        - /explore/compare
        - '/explore/compare/?p=Administrative%20Assistant%20(Full-time)&p=Game%20Development%20-%20Art&p=Accounting'
        - /explore/results
        - /explore/creative-arts
        - /explore/advanced-credentials
        - /explore/business-and-management
        - /explore/program/accounting
        - /explore/program/civil-engineering-technology
        - /explore/program/transportation-logistics-and-supply-chain-management
        - '/explore/program/transportation-logistics-and-supply-chain-management/?program-type=part-time-programm'
        - /international
        - /international/student-support/graduate-stories
        - /international/study-at-rrc/list-of-programs
        - /brazil/en
        - /brazil
        - /international/study-at-rrc
        - /international/live-in-manitoba
        - /international/work-and-immigration
        - /international/student-support
        - /international/how-to-apply
        - /international/404
        - '/maps/?campus=ndc&markers=indigenousSupports,security'
        - /alumni
        - /academic-news/2020/11/04/btm-work-packages
        - /ar/contact
        - /advising/rpl/contact
        - /alumni/contact/update
        - /contact
        - /administration/strategic-plan/measurements
        - /explore/program/communication-design
        - /administration/strategic-plan/commitments
        - /vtec
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ".wp-block-rrc-polytech-slider .swiper:before {\n  background: none !important;\n}\n.heroBanner {\n  background: none !important;\n}\n.rrc-InfiniteHits-item .wp-block-image.card-imge {\n  display: none !important;\n}\n"
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
