basic:
    name: 'RRC Polytech'
    environments:
        production: 'https://www.rrc.ca'
        staging: 'https://dev-83829-rrc.pantheonsite.io'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /truth-and-reconciliation/initiatives
        - /newsroom
        - /fundraising/donate
        - /about
        - /legal/accessibility
        - /administration
        - /governance
        - /hr
        - /media
        - /legal
        - /administration/president
        - /redgreen
        - /about/polytech
        - /alumni
        - /corporatesolutions
        - /fundraising
        - /marcom
        - /emergingmedia
        - /its
        - /tltc
        - /procurement
        - /safety
        - /shs
        - /truth-and-reconciliation
        - /academics
        - /explore
        - /explore/business-and-management
        - /explore/community-services
        - /explore/creative-arts
        - /explore/culinary
        - /explore/education
        - /explore/engineering-and-construction-technology
        - /explore/health-sciences
        - /indigenous
        - /explore/information-technology
        - /explore/skilled-trades
        - /explore/transportation-technology
        - /priceinstitute
        - /schroederinstitute
        - /academic-news
        - /annual-events
        - /convocation
        - /academicprep
        - /adultlearning
        - /academics/application-deadlines
        - /course-based-registration
        - /part-time/micro-credentials
        - /part-time
        - /techsolutions
        - /explore/opportunities
        - /future-students
        - /future-students/admission-requirements
        - /future-students/application-processes
        - /future-students/apprenticeship
        - /student
        - /future-students/intersession
        - /work-integrated-learning
        - /youth
        - /future-students/awards
        - /future-students/credit-for-prior-learning
        - /future-students/funding-your-education
        - /future-students/getting-ready-for-college
        - /future-students/connect-with-us
        - /future-students/dates
        - /future-students/fees
        - /future-students/recent-applicants-and-accepted-students
        - /recruitment
        - /services
        - /housing
        - /campusstore
        - /services/child-care
        - /parking
        - /facilityrentals
        - /health
        - /well-being/sport
        - /foodservices
        - /culex
        - /janes
        - /assessment
        - /services/student-service-centres
        - /services/tax-receipts
        - /supports
        - /academic-success
        - /advising
        - /careerservices
        - /indigenous/supports
        - /its/help-resources
        - /library
        - /diversity/resources/anti-racism
        - /diversity
        - /accessibility
        - /well-being
        - /counselling
        - /counselling/early-assist
        - /nowrongdoor
        - /supports/complaints
        - /supports/student-records
        - /assessment/exams
        - /campuses
        - /edc
        - /ndc
        - /stevenson
        - /interlake
        - /portage
        - /steinbach
        - /winkler
        - /research
        - /ar
        - /betac
        - /priceinstitute/camtt
        - /research/ecdr
        - /research-kitchen
        - /tacam
        - /vtec
        - /numbers
        - /global
        - /cni
        - /international
        - /annual-events/red-river-ready
        - '/explore/program/asl-english-interpretation/?program-type=full-time-program'
        - /explore/program/entertainment-production
        - /contact
        - /student/campus-tours
        - /hr/work/employment-opportunities
        - /careerservices/employers
        - '/maps/?campus=ndc'
        - /about/social-media
        - /future-partners
        - /simulation-centre
        - /about/privacy
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
